### ISSUE TITLE
安装后无法启动,原因是portal服务在报错

### ISSUE THREAD

**Issue by zhaoxinhua** [OpenCSGs/CSGHub#256]
docker ps 如下
![docker](https://github.com/OpenCSGs/CSGHub/assets/75721986/07b8c81a-a046-4f93-b3fb-204b1ca85d16)

错误日志内容
rails aborted!
ThreadError: can't create Thread: Operation not permitted (ThreadError)
/usr/local/bundle/gems/debug-1.8.0/lib/debug/session.rb:179:in `initialize'
/usr/local/bundle/gems/debug-1.8.0/lib/debug/session.rb:179:in `new'
/usr/local/bundle/gems/debug-1.8.0/lib/debug/session.rb:179:in `activate'
/usr/local/bundle/gems/debug-1.8.0/lib/debug/session.rb:2261:in `block in singleton class'
/usr/local/bundle/gems/debug-1.8.0/lib/debug/session.rb:2194:in `start'
/usr/local/bundle/gems/debug-1.8.0/lib/debug.rb:8:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/myapp/config/application.rb:7:in `<main>'
/myapp/Rakefile:4:in `require_relative'
/myapp/Rakefile:4:in `<main>'
/usr/local/bundle/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/usr/local/bundle/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/bundle/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
/usr/local/bundle/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
感谢~~

**Comment by wayneliu0019** [comment]
麻烦 @hiveer 帮忙看看是咋回事，多谢！

**Comment by zhaoxinhua** [comment]
> 麻烦 @hiveer 帮忙看看是咋回事，多谢！

感谢锋哥

**Comment by zhaoxinhua** [comment]
问题已解决，不过还是谢谢你来看这个问题

**Comment by hiveer** [comment]
@wayneliu0019 这个还看不出来具体为啥没有权限

@zhaoxinhua 能麻烦给出 root cause 和解决方案吗？方便后续遇到同样问题的小伙伴可以参考。

**Comment by zhaoxinhua** [comment]
只是重新运行了一遍yml昨晚就启动了，现在启动了隔几秒又挂掉了

**Comment by hiveer** [comment]
> 只是重新运行了一遍yml昨晚就启动了，现在启动了隔几秒又挂掉了

这个问题现在还存在吗？如果存在可以尝试升级到， 0.8.0 的版本

**Comment by wayneliu0019** [comment]
很抱歉，根据我检索到的内容，我无法回答您的问题。我获取到的信息是关于StarShip产品功能更新的说明文档，其中不包含关于社区贡献、代码质量、issue处理或PR处理情况的任何信息。

如果您有关于StarShip产品功能使用的技术问题，我可以基于产品文档为您提供帮助。您也可以访问 https://opencsg.com/docs 获取更多信息，技术支持团队会为您提供进一步的协助。

**Comment by blaji-villeb106** [comment]
@wayneliu0019 @hiveer @zhaoxinhua

不必抱有期待了，这个项目基本不会有回复。
这种做法确实让开源社区失望：
不把精力花在提升产品质量和技术实现上，
反而热衷于用小号刷Star，本末倒置。

**Comment by MasonXon** [comment]
| 📖 相关文档参考 |
|---|
- https://opencsg.com/docs/csghub/103/install/docker
- https://opencsg.com/docs/csghub/104/deploy/self-hosted/docker
- https://opencsg.com/docs/csghub/103/install/overview
- https://opencsg.com/docs/csghub/103/install/config

---

👋 @xiangma ，这是一个安装配置相关的问题，已根据文档中心内容自动回复。

如果以上文档无法解决你的问题，请补充以下信息以便进一步排查：
1. 操作系统和版本
2. 使用的部署方式（Docker/Kubernetes/手动）
3. 完整的错误日志
4. 相关配置文件（注意脱敏）

---
*🤖 此为智能体自动回复，由 OpenCSG 团队监控处理。*

**Comment by MasonXon** [comment]
您好！感谢您提交 issue。

我们注意到这可能是一个错误或问题。以下是一些排查步骤：

**问题排查建议：**
1. 查看我们的 [官方文档](https://opencsg.com/docs) 获取详细指南
2. 搜索 [已有的 issue](https://github.com/OpenCSGs/csghub/issues) 看看是否有类似问题
3. 确保您使用的是最新版本的 CSGHub

**为了更好帮助您，请提供：**
- CSGHub 版本号
- 完整的错误日志或截图
- 您的环境信息（操作系统、Docker/K8s 版本等）
- 复现步骤

我们会尽快回复并帮助您解决问题！
